name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main # Trigger on merge/push to main

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v4

            # If you use React/Vue/Sass, add your build steps here:
            # - name: Install and Build 🔧
            #   run: |
            #     npm install
            #     npm run build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build # Use 'dist' or 'build' if you have a build step
                  branch: gh-pages # The branch the action should deploy to
